<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $currencies = [
            ['iso_code' => 'AFN' , 'name' => 'Afghani', 'symbol' => '؋' ],
            ['iso_code' => 'ALL' , 'name' => 'Lek', 'symbol' => 'Lek' ],
            ['iso_code' => 'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ' ],
            ['iso_code' => 'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$' ],
            ['iso_code' => 'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$' ],
            ['iso_code' => 'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ' ],
            ['iso_code' => 'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман' ],
            ['iso_code' => 'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM' ],
            ['iso_code' => 'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$' ],
            ['iso_code' => 'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв' ],
            ['iso_code' => 'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$' ],
            ['iso_code' => 'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$' ],
            ['iso_code' => 'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b' ],
            ['iso_code' => 'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$' ],
            ['iso_code' => 'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$' ],
            ['iso_code' => 'BWP' , 'name' => 'Pula', 'symbol' => 'P' ],
            ['iso_code' => 'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => 'p.' ],
            ['iso_code' => 'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$' ],
            ['iso_code' => 'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$' ],
            ['iso_code' => 'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF' ],
            ['iso_code' => 'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$' ],
            ['iso_code' => 'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥' ],
            ['iso_code' => 'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$' ],
            ['iso_code' => 'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡' ],
            ['iso_code' => 'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱' ],
            ['iso_code' => 'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč' ],
            ['iso_code' => 'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr' ],
            ['iso_code' => 'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$' ],
            ['iso_code' => 'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£' ],
            ['iso_code' => 'EUR' , 'name' => 'Euro', 'symbol' => '€' ],
            ['iso_code' => 'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$' ],
            ['iso_code' => 'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£' ],
            ['iso_code' => 'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£' ],
            ['iso_code' => 'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£' ],
            ['iso_code' => 'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q' ],
            ['iso_code' => 'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$' ],
            ['iso_code' => 'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$' ],
            ['iso_code' => 'HNL' , 'name' => 'Lempira', 'symbol' => 'L' ],
            ['iso_code' => 'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn' ],
            ['iso_code' => 'HUF' , 'name' => 'Forint', 'symbol' => 'Ft' ],
            ['iso_code' => 'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp' ],
            ['iso_code' => 'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪' ],
            ['iso_code' => 'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼' ],
            ['iso_code' => 'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr' ],
            ['iso_code' => 'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$' ],
            ['iso_code' => 'JPY' , 'name' => 'Yen', 'symbol' => '¥' ],
            ['iso_code' => 'KGS' , 'name' => 'Som', 'symbol' => 'лв' ],
            ['iso_code' => 'KHR' , 'name' => 'Riel', 'symbol' => '៛' ],
            ['iso_code' => 'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩' ],
            ['iso_code' => 'KRW' , 'name' => 'Won', 'symbol' => '₩' ],
            ['iso_code' => 'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$' ],
            ['iso_code' => 'KZT' , 'name' => 'Tenge', 'symbol' => 'лв' ],
            ['iso_code' => 'LAK' , 'name' => 'Kip', 'symbol' => '₭' ],
            ['iso_code' => 'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£' ],
            ['iso_code' => 'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨' ],
            ['iso_code' => 'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$' ],
            ['iso_code' => 'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt' ],
            ['iso_code' => 'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls' ],
            ['iso_code' => 'MKD' , 'name' => 'Denar', 'symbol' => 'ден' ],
            ['iso_code' => 'MNT' , 'name' => 'Tugrik', 'symbol' => '₮' ],
            ['iso_code' => 'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨' ],
            ['iso_code' => 'MXN' , 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI)', 'symbol' => '$' ],
            ['iso_code' => 'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM' ],
            ['iso_code' => 'MZN' , 'name' => 'Metical', 'symbol' => 'MT' ],
            ['iso_code' => 'NGN' , 'name' => 'Naira', 'symbol' => '₦' ],
            ['iso_code' => 'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$' ],
            ['iso_code' => 'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr' ],
            ['iso_code' => 'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨' ],
            ['iso_code' => 'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$' ],
            ['iso_code' => 'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼' ],
            ['iso_code' => 'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.' ],
            ['iso_code' => 'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.' ],
            ['iso_code' => 'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php' ],
            ['iso_code' => 'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨' ],
            ['iso_code' => 'PLN' , 'name' => 'Zloty', 'symbol' => 'zł' ],
            ['iso_code' => 'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs' ],
            ['iso_code' => 'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼' ],
            ['iso_code' => 'RON' , 'name' => 'New Leu', 'symbol' => 'lei' ],
            ['iso_code' => 'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.' ],
            ['iso_code' => 'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб' ],
            ['iso_code' => 'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼' ],
            ['iso_code' => 'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$' ],
            ['iso_code' => 'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨' ],
            ['iso_code' => 'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr' ],
            ['iso_code' => 'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$' ],
            ['iso_code' => 'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£' ],
            ['iso_code' => 'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S' ],
            ['iso_code' => 'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$' ],
            ['iso_code' => 'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$' ],
            ['iso_code' => 'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£' ],
            ['iso_code' => 'THB' , 'name' => 'Baht', 'symbol' => '฿' ],
            ['iso_code' => 'TRY' , 'name' => 'Turkish Lira', 'symbol' => 'TL' ],
            ['iso_code' => 'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$' ],
            ['iso_code' => 'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$' ],
            ['iso_code' => 'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴' ],
            ['iso_code' => 'USD' , 'name' => 'US Dollar', 'symbol' => '$' ],
            ['iso_code' => 'UYU' , 'name' => 'UYI Peso Uruguayo Uruguay Peso en Unidades Indexadas', 'symbol' => '$U' ],
            ['iso_code' => 'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв' ],
            ['iso_code' => 'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs' ],
            ['iso_code' => 'VND' , 'name' => 'Dong', 'symbol' => '₫' ],
            ['iso_code' => 'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$' ],
            ['iso_code' => 'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼' ],
            ['iso_code' => 'ZAR' , 'name' => 'Rand', 'symbol' => 'R' ],
        ];

        Currency::insert($currencies);
    }
}
